# Generated by Django 5.0.6 on 2024-06-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_aula_oferta_disciplina_ofertadisciplina_aulas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertadisciplina',
            name='vagas',
            field=models.IntegerField(default=40),
        ),
    ]
